# Generated by Django 3.1.4 on 2021-01-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarra',
            name='marca',
            field=models.CharField(max_length=80),
        ),
    ]
