# Generated by Django 3.1.4 on 2021-01-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_guitarra_madera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guitarra',
            options={'ordering': ['-fecha_compra']},
        ),
    ]
