# Generated by Django 3.1.4 on 2021-01-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_auto_20210107_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitarra',
            name='madera',
            field=models.CharField(default='No informada', max_length=20),
        ),
    ]
