# Generated by Django 3.1.4 on 2021-01-11 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_auto_20210111_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarra',
            name='musico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='formularios.musico'),
        ),
    ]
