# Generated by Django 3.1.4 on 2021-01-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_auto_20210108_0435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guitarra',
            options={'ordering': ['-marca']},
        ),
    ]
