# Generated by Django 3.1.4 on 2021-01-07 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_guitarra_madera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('guitarra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.guitarra')),
            ],
        ),
    ]
