# Generated by Django 3.1.4 on 2021-01-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_auto_20210111_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasaporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha_expiracion', models.DateField()),
                ('musico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formularios.musico')),
            ],
        ),
    ]
