# Generated by Django 3.1.4 on 2021-01-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0007_auto_20210113_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
