# Generated by Django 3.1.4 on 2021-01-15 06:28

import django.core.validators
from django.db import migrations, models
import formularios.models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0008_extension_nombre_musico_a_250'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarraCBV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(4, 'Marca debe tener 4 caracteres mínimo!')])),
                ('modelo', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'El modelo no puede ser de menos de 2 letras')])),
                ('cuerdas', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, 'Número entre 6 y 10'), django.core.validators.MinValueValidator(6, 'Número entre 6 y 10')])),
                ('madera', models.CharField(default='No informada', max_length=20)),
                ('fecha_compra', models.DateField(validators=[formularios.models.validar_fecha])),
            ],
        ),
    ]
