# Generated by Django 3.1.5 on 2021-01-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0009_guitarracbv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guitarra',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='guitarracbv',
            options={'ordering': ['id']},
        ),
    ]
