# Generated by Django 3.1.5 on 2021-01-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ex', '0002_profile_archivo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.CharField(default='sin asignar', max_length=50),
        ),
    ]
